    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>

                    <form action="<?php echo BASE; ?>usuario/cadastrar/" class="form-horizontal" method="post">

                        <div class="form-group">
                            <label for="name" class="col-sm-3 control-label">Nome:</label>

                            <div class="col-sm-8">
                                <input required  type="text" name="name" class="form-control" id="name" value="<?php echo $this->request->post('name') ?>" placeholder="nome do usuario">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-sm-3 control-label">E-mail:</label>

                            <div class="col-sm-8">
                                <input required  type="email" name="email" class="form-control" id="email" value="<?php echo $this->request->post('email') ?>" placeholder="example@example.com">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Usuário:</label>

                            <div class="col-sm-8">
                                <input required  type="text" name="username" class="form-control" id="username" value="<?php echo $this->request->post('username') ?>" placeholder="login">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Senha:</label>

                            <div class="col-sm-8">
                                <input required  type="password" name="password" class="form-control" id="password" placeholder="Sua senha">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-8 col-sm-10">
                                <button type="submit" class="btn btn-default">Cadastrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
