    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <div class="alert alert-block alert-warning">
                        <h4>
                            Recupere sua senha.
                        </h4>
                            Um link de redefinição será enviado para seu e-mail. Por favor, verifique sua caixa de SPAM.
                    </div>

                    <form  class="form-horizontal">

                        <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Usuário:</label>

                            <div class="col-sm-9">
                                <input type="text" name="username" class="form-control" id="username" value="<?php echo $this->request->post('username') ?>" placeholder="login">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-7 col-sm-10">
                                <button type="submit" class="btn btn-default">Enviar link de redefinição</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
