    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>

                    <form action="<?php echo BASE; ?>login/logar/" class="form-horizontal" method="post">

                        <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Usuário:</label>

                            <div class="col-sm-8">
                                <input type="text" name="username" class="form-control" id="username" value="<?php echo $this->request->post('username') ?>" placeholder="login">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Senha:</label>

                            <div class="col-sm-8">
                                <input type="password" name="password" class="form-control" id="password" placeholder="Sua senha">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-7 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> Esqueci minha Senha
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-9 col-sm-10">
                                <button type="submit" class="btn btn-default">Logar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
